### ISSUE TITLE
Error get_cluster

### ISSUE THREAD

**Issue by AndriiShchur** [cloudyr/AzureContainers#1]
How I can fix this error

Error in process_response(res, match.arg(http_status_handler)) : 
  Not Found (HTTP 404). Failed to complete Resource Manager operation. Message:
Could not find role name: clusterUser in subscription: MYSUBSCRIPTION, resourceGroup: MYGROUP, managed cluster
resource: MUCLUST.

**Comment by Hong-Revo** [comment]
Can you share the code you ran that produced that error?

**Comment by AndriiShchur** [comment]
library(AzureContainers)
library(AzureRMR)
library(httpuv)

Sys.setenv(TZ = 'Europe/Kiev')

az <- az_rm$new(tenant="",
                app="",
                password="")


# create a resource group for our deployments
sub <- az$get_subscription("")


# create container registry ---
# create a resource group for our deployments
rg <- sub$create_resource_group("deployresgrp", location="West Europe")

# create container registry
deployreg_svc <- rg$create_acr('mysmartacr', location = "West Europe",
                                         admin_user_enabled = TRUE, sku = "Basic")

deployreg <- deployreg_svc$get_docker_registry()
deployreg$push("")

# create a Kubernetes cluster with 2 nodes, running Linux
deployclus_svc <- rg$create_aks('first', location = 'West Europe', login_user = 'clusterUser',
                                 dns_prefix ='testtwo', kubernetes_version = '1.12.4',
                                 enable_rbac = FALSE, agent_pools = aks_pools("pool1", 2), wait = TRUE)

# get the cluster endpoint
deployclus <- deployclus_svc$get_cluster()

**Comment by Hong-Revo** [comment]
Something weird is going on with Azure. At first I got the error you mention, but now I get a different one:

```
Error in process_response(res, match.arg(http_status_handler)) :
  Bad Request (HTTP 400). Failed to complete Resource Manager operation. Message:
UnmarshalEntity encountered error: json: cannot unmarshal object into
Go struct field ServicePrincipalProfile.secret of type string.
```

Maybe try again in 24 hours? Azure was experiencing some glitches yesterday, it's possible things haven't been completely cleared up.

Also: if you want to have a login user, you also need to specify an SSH key in the `login_passkey` argument.

**Comment by Hong-Revo** [comment]
To clarify: the 404 error you're getting seems to be due to a change in the AKS backend somewhere. I'm in the process of tracking it down.

The `login_passkey` arg is unrelated, and is just something I noticed on reading your code. If you want to be able to ssh into your worker nodes, you specify _both_ `login_user` and `login_passkey` in the `create_aks` call: `rg$create_aks('first', ..., login_user='clusterUser', login_passkey='<ssh_key>'`. If you don't need to ssh into your nodes, then you can leave these arguments out.

**Comment by AndriiShchur** [comment]
Thank You.

It  solved my problem !
